### ISSUE TITLE
no module named `qpack` when running setup.py

### ISSUE THREAD

**Issue by joente** [SiriDB/siridb-connector#9]
```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dzrqntcx/siridb-connector/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dzrqntcx/siridb-connector/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gchcwegz
         cwd: /tmp/pip-install-dzrqntcx/siridb-connector/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dzrqntcx/siridb-connector/setup.py", line 11, in <module>
        from siridb.connector import __version__
      File "/tmp/pip-install-dzrqntcx/siridb-connector/siridb/connector/__init__.py", line 4, in <module>
        from .lib.protocol import _SiriDBProtocol
      File "/tmp/pip-install-dzrqntcx/siridb-connector/siridb/connector/lib/protocol.py", line 7, in <module>
        import qpack
    ModuleNotFoundError: No module named 'qpack'
```

**Comment by joente** [comment]
Resolved in 2.0.8
